accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    # 로그인/회원가입 페이지 url
    path("", views.accounts, name="index"),
    # 회원가입 url
    path("sign_up/", views.sign_up, name="sign_up"),
    # 로그인 url
    path("login/", views.login, name="login"),
    # 작가 페이지에서 대시보드 페이지 url
    path("my_writer/", views.my_writer, name="my_writer"),
    # 작품 등록 페이지 url
    path("my_writer/painting/", views.my_writer_painting, name="my_writer_painting"),
    # 전시 등록 페이지 url
    path("my_writer/exhibition/", views.my_writer_exhibition, name="my_writer_exhibition"),
]

config/urls.py
# from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("writers/", include("writers.urls")),
]

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models


class CustomUserManager(BaseUserManager):
    """
    Assignee : 상백

    custom user model을 사용하기 위해 UserManager 클래스와 create_user, create_superuser 함수 정의
    user 생성 시, email를 필수로 지정
    """

    def create_user(self, email, password):
        if not email:
            raise ValueError("Users must have an email")
        user = self.model(
            email=email,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        """python manage.py createsuperuser 사용 시 해당 함수가 사용됨"""
        user = self.create_user(
            email=email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    """
    Assignee : 상백

    User 모델을 커스텀해서 생성하는 클래스 정의
    이메일, 이름, 성별, 연락처, 생년월일 필드 설정
    """

    id = models.BigAutoField(primary_key=True)
    email = models.EmailField("이메일", max_length=100, unique=True)
    password = models.CharField("비밀번호", max_length=128)
    username = models.CharField("이름", max_length=16)
    gender = models.CharField("성별", max_length=2)
    mobile = models.CharField("연락처", max_length=20)
    birth = models.DateField("생년월일", null=True)

    """is_active가 False일 경우 계정이 비활성화됨"""
    is_active = models.BooleanField("활성화", default=True)

    """is_staff에서 해당 값 사용"""
    is_admin = models.BooleanField("관리자", default=False)

    created_at = models.DateTimeField("작성시간", auto_now_add=True)
    updated_at = models.DateTimeField("수정시간", auto_now=True)

    """"
    # id로 사용 할 필드 지정.
    # 로그인 시 USERNAME_FIELD에 설정 된 필드와 password가 사용된다.
    """
    USERNAME_FIELD = "email"

    """user를 생성할 때 입력받을 필드 지정"""
    REQUIRED_FIELDS = []

    """custom user 생성 시 필요"""
    objects = CustomUserManager()

    def __str__(self):
        return f"email: {self.email} / name: {self.username}"

    def has_perm(self, perm, obj=None):
        """
        # 로그인 사용자의 특정 테이블의 crud 권한을 설정, perm table의 crud 권한이 들어간다.
        # admin일 경우 항상 True, 비활성 사용자(is_active=False)의 경우 항상 False
        """
        return True

    def has_module_perms(self, app_label):
        """ "
        # 로그인 사용자의 특정 app에 접근 가능 여부를 설정, app_label에는 app 이름이 들어간다.
        # admin일 경우 항상 True, 비활성 사용자(is_active=False)의 경우 항상 False
        """
        return True

    @property
    def is_staff(self):
        """admin 권한 설정"""
        return self.is_admin

accounts/views.py
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from accounts.models import User
from writers.models import Exhibition, Painting


# url : GET accounts/
def accounts(request):
    """
    Assignee : 상백

    로그인 또는 회원가입을 진행할 수 있는 페이지
    """

    return render(request, "accounts/index.html")


# url : GET,POST accounts/sign_up/
def sign_up(request):
    """
    Assignee : 상백

    GET : 회원가입을 진행할 수 있는 페이지 구현
    회원가입 시, html type를 이용해서 이메일과 전화번호, 생년월일 형식 지정
    ex) aaa@naver.com, 010-6223-8078, 1995-01-17
    POST : 회원가입 진행 로직 구현, 회원가입 완료 시 로그인 진행
    """

    context = {}

    if request.method == "POST":
        if (
            request.POST.get("email")
            and request.POST.get("password")
            and request.POST.get("password") == request.POST.get("password_check")
        ):

            new_user = User.objects.create_user(
                email=request.POST.get("email"),
                password=request.POST.get("password"),
            )
            auth.login(request, new_user)

            user = User.objects.get(email=request.user.email)
            user.username = request.POST.get("username")
            user.gender = request.POST.get("gender")
            user.mobile = request.POST.get("mobile")
            user.birth = request.POST.get("birth")
            user.save()

            return redirect("accounts:index")
        else:
            context["error"] = "회원가입 입력사항을 다시 확인해주세요!"

    return render(request, "accounts/sign_up.html", context)


# url : POST accounts/login/
def login(request):
    """
    Assignee : 상백

    가입한 이메일 및 비밀번호로 로그인할 수 있도록 로직 구성
    auth로 인증이 되면 로그인 실행
    """

    context = {}

    if request.method == "POST":
        if request.POST.get("email") and request.POST.get("password"):
            print(request.POST.get("email"))
            print(request.POST.get("password"))
            user = auth.authenticate(request, email=request.POST.get("email"), password=request.POST.get("password"))

            if user is not None:
                auth.login(request, user)
                return redirect("accounts:index")
            else:
                context["error"] = "이메일과 비밀번호를 다시 입력해주세요!"
        else:
            context["error"] = "이메일과 비밀번호를 모두 입력해주세요!"
    return render(request, "accounts/index.html", context)


# url : GET accounts/my_writer/
@login_required
def my_writer(request):
    """
    Assignee : 상백

    작가로 등록된 계정만 페이지를 조회할 수 있도록 if문 설정
    작가인 본인의 정보를 확인하고 등록된 작품과 전시를 확인 가능
    작품 및 전시 등록 버튼 설정
    """

    if request.user.writer.approval == True:
        user = request.user
        writer = user.writer

        context = {
            "writer": writer,
        }

        return render(request, "accounts/my_writer.html", context)
    else:
        return redirect("writers:list")


# url : GET,POST accounts/my_writer/painting/
def my_writer_painting(request):
    """
    Assignee : 상백

    GET : 작품 등록 페이지 구현
    html type을 이용해 제목 64자 이하 / 가격 0 이상 숫자 / 호수 1 이상 500 이하 숫자 설정
    POST : 작품 등록 로직 구현
    위의 정보 중 하나라도 없을 경우, context 딕셔너리로 에러 메시지 응답
    입력된 정보로 Painting 모델 객체 생성
    """

    context = {}

    if request.method == "POST":
        if request.POST.get("title") and request.POST.get("price") and request.POST.get("size"):
            title = request.POST.get("title")
            price = request.POST.get("price")
            size = request.POST.get("size")
            painting = Painting(title=title, price=price, size=size, writer=request.user.writer)
            painting.save()
            return redirect("accounts:my_writer")
        else:
            context["error"] = "등록 입력사항을 다시 확인해주세요!"
            return render(request, "accounts/my_writer_painting.html", context)
    else:
        return render(request, "accounts/my_writer_painting.html")


# url : GET,POST accounts/my_writer/exhibition/
def my_writer_exhibition(request):
    """
    Assignee : 상백

    GET : 전시 등록 페이지 구현
    html type을 이용해 제목 64자 이하 / 시작일과 종료일 캘린더 설정 / 작품 목록 선택 가능하게 설정
    작품 선택의 경우, Painting 모델과 Exhibition 모델을 1:1 관계로 설정해서 하나의 작품에 대한 전시를 진행한다고 생각
    POST : 전시 등록 로직 구현
    위의 정보 중 하나라도 없을 경우, context 딕셔너리로 에러 메시지 응답
    입력된 정보로 exhibition 모델 객체 생성
    """

    context = {}

    if request.method == "POST":
        if (
            request.POST.get("title")
            and request.POST.get("start")
            and request.POST.get("end")
            and request.POST.get("painting")
        ):
            title = request.POST.get("title")
            start = request.POST.get("start")
            end = request.POST.get("end")
            painting = Painting.objects.get(id=request.POST.get("painting"))
            exhibition = Exhibition(title=title, start=start, end=end, writer=request.user.writer, painting=painting)
            exhibition.save()
            return redirect("accounts:my_writer")
        else:
            context["error"] = "등록 입력사항을 다시 확인해주세요!"
            return render(request, "accounts/my_writer_exhibition.html", context)
    else:
        paintings = Painting.objects.filter(writer=request.user.writer)

        context = {
            "paintings": paintings,
        }

        return render(request, "accounts/my_writer_exhibition.html", context)

accounts/templates/accounts/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <title>OpenGallery</title>
</head>
<body>
    <div>
        <h1>로그인</h1>

         <!-- 에러 메시지 띄우기 -->
         <div id="login-error-box">
            {% if error %}
                <div id="login-error">
                    {{ error }}
                </div>
            {% endif %}
        </div>

        <!-- 로그인 상태 나타내주기 -->
        <div id="login-status">
            {% if request.user %}
                {{ request.user.email }}님, 환영합니다!
            {% endif %}
        </div>
    </div>

    <div>
        <!-- 로그인 정보 받기 -->
        <form method="POST" action="{% url 'accounts:login' %}" enctype="multipart/form-data"> 
            {% csrf_token %}
            <div id="login-form-box">
                <div id="login-form1">
                    <label  class="form-label" for="email">이메일</label>
                    <input class="form-control" type="email" id="email" name="email" placeholder="이메일">
                </div>
                <div id="login-form2">
                    <label  class="form-label" for="password">비밀번호</label>
                    <input class="form-control" type="password" id="password" name="password" placeholder="비밀번호">
                </div>
                <button type="submit" id="login_button" style="margin-top: 20px">로그인</button>
            </div>
    </div>

    <br>

    <div>
        <a href="{% url 'accounts:sign_up' %}">회원가입</a>
    </div>
</body>
</html>

accounts/templates/accounts/my_writer.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <title>OpenGallery</title>
</head>
<body>
<h1>작가 페이지 대시보드</h1>

<p>이름 : {{ writer.name }}</p>
<p>성별 : {{ writer.gender }}</p>
<p>생년월일 : {{ writer.birth }}</p>
<p>이메일 : {{ writer.email }}</p>
<p>연락처 : {{ writer.mobile }}</p>

<h2>등록된 작품 목록</h2>
{% for paint in writer.writer_painting.all %}
<p>작품명 : {{ paint.title }}</p>
{% endfor %}

<h2>등록된 전시 목록</h2>
{% for exhibition in writer.writer_exhibition.all %}
<p>전시명 : {{ exhibition.title }}</p>
{% endfor %}

<br>

<div>
    <a href="{% url 'accounts:my_writer_painting' %}">작품 등록하기</a>
</div>

<div>
    <a href="{% url 'accounts:my_writer_exhibition' %}">전시 등록하기</a>
</div>

</body>
</html>

accounts/templates/accounts/my_writer_exhibition.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <title>OpenGallery</title>
</head>
<body>
<h1>전시 등록 페이지</h1>

<!-- 에러 메시지 띄우기 -->
<div id="my_writer_exhibition-error-box">
    {% if error %}
        <div id="my_writer_exhibition-error">
            {{ error }}
        </div>
    {% endif %}
</div>

<div>
    <!-- 전시 등록 정보 받기 -->
    <form method="POST" action="{% url 'accounts:my_writer_exhibition' %}" enctype="multipart/form-data"> 
        {% csrf_token %}
        <div id="my_writer_exhibition-form-box">
            <div id="my_writer_exhibition-form-box">
                <div id="my_writer_exhibition-form1">
                    <label class="form-label" for="title">제목</label>
                    <input class="form-control" type="text" maxlength='64' id="title" name="title" placeholder="제목">
                </div>
                <div id="my_writer_exhibition-form2">
                    <label class="form-label" for="start">시작일</label>
                    <input class="form-control" type="date" id="start" name="start" placeholder="시작일">
                </div>
                <div id="my_writer_exhibition-form3">
                    <label class="form-label" for="end">종료일</label>
                    <input class="form-control" type="date" id="end" name="end" placeholder="종료일">
                </div>
                <div id="my_writer_exhibition-form4">
                    <select name="painting" id="painting">
                        <option disabled selected>작품목록 선택</option>
                        {% for painting in paintings %}
                        <option value="{{ painting.id }}">{{ painting.title }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <button type="submit" id="my_writer_exhibition_button" style="margin-top: 20px">전시 등록하기</button>
        </div>
</div>

</body>
</html>

accounts/templates/accounts/my_writer_painting.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <title>OpenGallery</title>
</head>
<body>
<h1>작품 등록 페이지</h1>

<!-- 에러 메시지 띄우기 -->
<div id="my_writer_painting-error-box">
    {% if error %}
        <div id="my_writer_painting-error">
            {{ error }}
        </div>
    {% endif %}
</div>

<div>
    <!-- 작품 등록 정보 받기 -->
    <form method="POST" action="{% url 'accounts:my_writer_painting' %}" enctype="multipart/form-data"> 
        {% csrf_token %}
        <div id="my_writer_painting-form-box">
            <div id="my_writer_painting-form-box">
                <div id="my_writer_painting-form1">
                    <label class="form-label" for="title">제목</label>
                    <input class="form-control" type="text" maxlength='64' id="title" name="title" placeholder="제목">
                </div>
                <div id="my_writer_painting-form2">
                    <label class="form-label" for="price">가격</label>
                    <input class="form-control" type="number" min="1" id="price" name="price" placeholder="가격">
                </div>
                <div id="my_writer_painting-form3">
                    <label class="form-label" for="size">호수</label>
                    <input class="form-control" type="number" min="1" max="500" id="size" name="size" placeholder="호수">
                </div>
            </div>
            <button type="submit" id="my_writer_painting_button" style="margin-top: 20px">작품 등록하기</button>
        </div>
</div>

</body>
</html>

accounts/templates/accounts/sign_up.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <title>OpenGallery</title>
</head>
<body>
    <div>
        <h1>회원가입</h1>

        <!-- 에러 메시지 띄우기 -->
        <div id="signup-error-box">
            {% if error %}
                <div id="signup-error">
                    {{ error }}
                </div>
            {% endif %}
        </div>
    </div>
    <div>
        <!-- 회원가입 정보 받기 -->
        <form method="POST" action="{% url 'accounts:sign_up' %}" enctype="multipart/form-data"> 
            {% csrf_token %}
            <div id="signup-form-box">
                <div id="signup-form1">
                    <label  class="form-label" for="email">이메일</label>
                    <input class="form-control" type="email" id="email" name="email" placeholder="이메일">
                </div>
                <div id="signup-form2">
                    <label  class="form-label" for="password">비밀번호</label>
                    <input class="form-control" type="password" id="password" name="password" placeholder="비밀번호">
                </div>
                <div id="signup-form3">
                    <label  class="form-label" for="password_check">비밀번호 확인</label>
                    <input class="form-control" type="password" id="password_check" name="password_check" placeholder="비밀번호 확인">
                </div>
                <div id="signup-form4">
                    <label  class="form-label" for="username">이름</label>
                    <input class="form-control" type="text" id="username" name="username" placeholder="이름">
                </div>
                <div id="signup-form5">
                    <label  class="form-label" for="gender">성별</label>
                    <label><input class="form-control" type="checkbox" id="gender" name="gender" value="male">남자</label>
                    <label><input class="form-control" type="checkbox" id="gender" name="gender" value="female">여자</label>
                </div>
                <div id="signup-form6">
                    <label  class="form-label" for="mobile">연락처</label>
                    <input class="form-control" type="tel" id="mobile" name="mobile" pattern="[0-9]{2,3}-[0-9]{3,4}-[0-9]{3,4}" placeholder="연락처">
                </div>
                <div id="signup-form7">
                    <label  class="form-label" for="birth">생년월일</label>
                    <input class="form-control" type="date" id="birth" name="birth" placeholder="생년월일">
                </div>

                <button type="submit" id="signup_button" style="margin-top: 20px">회원가입</button>
            </div>
    </div>
</body>
</html>