config/urls.py
# from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("writers/", include("writers.urls")),
]

writers/urls.py
from django.urls import path

from . import views

app_name = "writers"

urlpatterns = [
    # 작가 목록 조회 페이지 url
    path("", views.list, name="list"),
    # 작품 목록 조회 페이지 url
    path("painting/", views.painting, name="painting"),
    # 작가 등록 신청 페이지 url
    path("register/", views.register, name="register"),
    # 관리자 대시보드 페이지 url
    path("admin/", views.admin, name="admin"),
    # 작가 등록 신청 내역 조회 페이지 url
    path("admin/register/", views.admin_register, name="admin_register"),
    # 작가 통계 페이지 url
    path("admin/statistics/", views.admin_statistics, name="admin_statistics"),
]

writers/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from accounts.models import User


class Writer(models.Model):
    """
    Assignee : 상백

    User 모델과 1:1 관계가 형성되어 있는 Writer 작가 모델 정의
    성별은 남/여 선택할 수 있도록 카테고리 설정
    작가 등록 시 approval 필드 True로 변경하고 해당 작가와 문제가 있을 경우, False로 등록 보류 가능하도록 설정
    """

    class Category(models.TextChoices):
        male = "male"
        female = "female"

    name = models.CharField("이름", max_length=16)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    gender = models.CharField("성별", max_length=10, choices=Category.choices)
    birth = models.DateField("생년월일")
    email = models.EmailField("이메일", max_length=100, unique=True)
    mobile = models.CharField("연락처", max_length=20)
    approval = models.BooleanField(default=False, null=True, blank=True)
    created_at = models.DateTimeField("등록일자", auto_now_add=True)
    updated_at = models.DateTimeField("수정일자", auto_now=True)


class Painting(models.Model):
    """
    Assignee : 상백

    Writer 모델과 1:N 관계가 형성되어 있는 Painting 작품 모델 정의
    가격은 0 이상, 호수는 1 이상 500 이하의 숫자를 설정하기 위해 django에서 제공하는 validator 사용
    """

    title = models.CharField("제목", max_length=64)
    writer = models.ForeignKey("Writer", on_delete=models.CASCADE, related_name="writer_painting")
    price = models.PositiveIntegerField("가격", default=0)
    size = models.IntegerField("호수", validators=[MinValueValidator(1), MaxValueValidator(500)])
    created_at = models.DateTimeField("등록일자", auto_now_add=True)
    updated_at = models.DateTimeField("수정일자", auto_now=True)


class Exhibition(models.Model):
    """
    Assignee : 상백

    Writer 모델과 1:N 관계가 형성되어 있는 Exhibition 전시 모델 정의
    Painting 모델과는 1:1 관계 설정 - 1명의 작가의 작품만 전시된다고 판단
    """

    title = models.CharField("제목", max_length=64)
    writer = models.ForeignKey("Writer", on_delete=models.CASCADE, related_name="writer_exhibition")
    painting = models.OneToOneField(Painting, on_delete=models.PROTECT, null=True)
    start = models.CharField("시작일", max_length=12)
    end = models.CharField("종료일", max_length=12)
    created_at = models.DateTimeField("등록일자", auto_now_add=True)
    updated_at = models.DateTimeField("수정일자", auto_now=True)

writers/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from .models import Painting, Writer


# url : GET writers/
def list(request):
    """
    Assignee : 상백

    작가 목록을 조회할 수 있는 페이지 구현
    최근에 등록된 순서대로 조회할 수 있게 ORM 메소드인 order_by를 created_at 내림차순으로 설정하고
    작가 등록 신청이 완료된 작가들만 보여주기 위해 approval=True 필터링 조건 설정
    작가 이름, 성별, 생년월일, 연락처 정보 응답
    """

    writers = Writer.objects.filter(approval=True).order_by("-created_at")

    context = {
        "writers": writers,
    }

    return render(request, "writers/list.html", context)


# url : GET writers/painting/
def painting(request):
    """
    Assignee : 상백

    작품 목록을 조회할 수 있는 페이지 구현
    최근에 등록된 순서대로 조회할 수 있게 ORM 메소드인 order_by를 created_at 내림차순으로 설정
    작품 제목, 가격, 호수, 작가 정보 응답
    작가로 승인된 작가의 작품들만 볼 수 있게 html에 django template language 설정
    """

    paintings = Painting.objects.all().order_by("-created_at")

    context = {
        "paintings": paintings,
    }

    return render(request, "writers/painting.html", context)


# url : GET,POST writers/register/
@login_required
def register(request):
    """
    Assignee : 상백

    GET : 작가 등록 신청을 할 수 있는 페이지 구현
    @login_required로 로그인을 해야 접근할 수 있게 설정
    로그인이 된 이후에는, 작가 등록 승인이 되지 않은 상황이면 접근이 가능하고 승인이 되었다면 작가 리스트 화면으로 redirect 하게끔 설정
    POST : 작가 등록 신청 로직 구현
    html의 input - type 요소를 이용해서 이름 16자 이하 / 성별 남여 선택 / 이메일 형식 / 생년월일 캘린더 선택 / 연락처 pattern 지정으로
    입력 정보 형식 설정
    위의 정보가 하나라도 없을 경우 context에 에러 메시지 추가해서 html에 보여주도록 설정
    신청 단계로 approval 필드는 False로 지정
    """

    context = {}

    if hasattr(request.user, "writer"):
        if request.user.writer.approval == False:
            return render(request, "writers/register.html", context)
        else:
            return redirect("writers:list")
    else:
        if request.method == "POST":
            if (
                request.POST.get("name")
                and request.POST.get("gender")
                and request.POST.get("birth")
                and request.POST.get("email")
                and request.POST.get("mobile")
            ):
                user = request.user
                name = request.POST.get("name")
                gender = request.POST.get("gender")
                birth = request.POST.get("birth")
                email = request.POST.get("email")
                mobile = request.POST.get("mobile")
                writer = Writer(
                    user=user, name=name, gender=gender, birth=birth, email=email, mobile=mobile, approval=False
                )
                writer.save()
                return redirect("writers:list")
            else:
                context["error"] = "등록 입력사항을 다시 확인해주세요!"
                return render(request, "writers/register.html", context)
        else:
            return render(request, "writers/register.html", context)


# url : GET writers/admin/
def admin(request):
    """
    Assignee : 상백

    관리자 대시보드 페이지 구현
    해당 페이지에서 작가 등록 신청 내역 조회 페이지 및 작가 통계 페이지로 이동할 수 있게 a element 설정
    관리자만 해당 페이지를 볼 수 있게 if문 설정
    """

    if request.user.is_admin == True:
        return render(request, "writers/admin.html")
    else:
        return redirect("writers:list")


# url : GET,POST writers/admin/register/
def admin_register(request):
    """
    Assignee : 상백

    GET : 작가 등록 신청 내역을 조회할 수 있는 페이지 구현
    신청자 정보를 최신순으로 표기
    POST : 작가 등록 신청 승인 로직 구현
    원하는 신청자 체크박스 선택 후 버튼 클릭 시, 신청자 id 정보를 받아 조회하고 approval 필드가 False일 경우에만 True로 수정해서 승인 진행
    승인 완료 후에는 작가 리스트에 추가됨을 확인하기 위해 작가 목록 리스트 redirect
    """

    if request.method == "POST":
        register_id = request.POST.get("admin_register")
        writer = Writer.objects.get(id=register_id)
        if writer.approval == False:
            writer.approval = True
            writer.save()
            return redirect("writers:list")
    else:
        writers = Writer.objects.filter(approval=False).order_by("-created_at")

    writers = Writer.objects.filter(approval=False).order_by("-created_at")
    context = {
        "writers": writers,
    }

    return render(request, "writers/admin_register.html", context)


# url : GET writers/admin/statistics/
def admin_statistics(request):
    """
    Assignee : 상백

    작가 통계 페이지 구현
    등록된 총 작품 개수 / 등록된 총 작가 수 / 승인대기 중인 작가 수 응답
    요구사항인 작가별 100호 이하 작품 개수 및 작품 평균 가격은 구현하지 못함
    """

    paintings_count = Painting.objects.all().count()
    writers_count = Writer.objects.filter(approval=True).count()
    before_writers_count = Writer.objects.filter(approval=False).count()
    writers = Writer.objects.filter(approval=True).order_by("-created_at")

    context = {
        "paintings_count": paintings_count,
        "writers_count": writers_count,
        "before_writers_count": before_writers_count,
        "writers": writers,
    }

    return render(request, "writers/admin_statistics.html", context)

writers/templates/writers/admin.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <title>OpenGallery</title>
</head>
<body>
<h1>관리자 대시보드 페이지</h1>
    <div>
        <a href="{% url 'writers:admin_register' %}">작가 등록 신청 내역 조회 페이지</a>
    </div>

    <div>
        <a href="{% url 'writers:admin_statistics' %}">작가 통계 페이지</a>
    </div>
</body>
</html>

writers/templates/writers/admin_register.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <title>OpenGallery</title>
</head>
<body>
<h1>작가 등록 신청 내역 조회 페이지</h1>

<table border="1">
	<th>이름</th>
	<th>성별</th>
    <th>생년월일</th>
    <th>이메일</th>
    <th>연락처</th>
    <th>신청 일시</th>
    <th>승인/반려 상태</th>
    <th>승인 하기</th>
    {% if writers %}
    {% for writer in writers %}
    <tr><!-- 테이블 줄 시작 -->
        <td>{{ writer.name }}</td>
        <td>{{ writer.gender }}</td>
        <td>{{ writer.birth }}</td>
        <td>{{ writer.email }}</td>
        <td>{{ writer.mobile }}</td>
        <td>{{ writer.created_at }}</td>
        <td>{{ writer.approval }}</td>
        <td>
            <form method="POST" action="{% url 'writers:admin_register' %}" enctype="multipart/form-data"> 
                {% csrf_token %}
                <div id="admin_register-form">
                    <label><input class="form-control" type="checkbox" id="admin_register" name="admin_register" value="{{ writer.id }}"></label>
                </div>
        </td>
    </tr><!-- 테이블 줄 끝 -->
    {% endfor %}
    {% endif %}
</table>
    <button type="submit" id="admin_register_button" style="margin-top: 20px">작가 등록 신청 승인하기</button>
</body>
</html>

writers/templates/writers/admin_statistics.html
{% load my_filter %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <title>OpenGallery</title>
</head>
<body>
<h1>작가 통계 페이지</h1>

<p>등록된 총 작품 수: {{ paintings_count }}</p>
<p>등록된 총 작가 수: {{ writers_count }}</p>
<p>승인대기 중인 작가 수: {{ before_writers_count }}</p>

<table border="1">
	<th>이름</th>
	<th>100호 이하 작품 개수</th>
    <th>작품의 평균 가격</th>

    {% if writers %}
    {% for writer in writers %}
    <tr><!-- 테이블 줄 시작 -->
        <td>{{ writer.name }}</td>
        <td>미구현</td>
        <td>미구현</td>
    </tr><!-- 테이블 줄 끝 -->
    {% endfor %}
    {% endif %}
</table>

</body>
</html>

writers/templates/writers/list.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <title>OpenGallery</title>
</head>
<body>
<h1>작가 목록 리스트</h1>
{% for writer in writers %}
    <p>이름 : {{ writer.name }}</p>
    성별 : {{ writer.gender }}
    생년월일 : {{ writer.birth }}
    연락처 : {{ writer.mobile }}
    <br>
{% endfor %}
</body>
</html>

writers/templates/writers/painting.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <title>OpenGallery</title>
</head>
<body>
<h1>작품 목록 리스트</h1>
{% for painting in paintings %}
{% if painting.writer.approval == True %}
    <p>제목 : {{ painting.title }}</p>
    가격 : ₩{{ painting.price|floatformat:"0g" }}
    호수 : {{ painting.size }}
    작가 : {{ painting.writer.name }}
    <br>
{% endif %}
{% endfor %}
</body>
</html>

writers/templates/writers/register.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <title>OpenGallery</title>
</head>
<body>
<h1>작가 등록 신청하기</h1>

<!-- 에러 메시지 띄우기 -->
<div id="register-error-box">
    {% if error %}
        <div id="register-error">
            {{ error }}
        </div>
    {% endif %}
</div>

<br>

<div>
    <!-- 작가 등록 정보 받기 -->
    <form method="POST" action="{% url 'writers:register' %}" enctype="multipart/form-data"> 
        {% csrf_token %}
        <div id="register-form-box">
            <div id="register-form-box">
                <div id="register-form1">
                    <label class="form-label" for="email">이메일</label>
                    <input class="form-control" type="email" id="email" name="email" placeholder="이메일">
                </div>
                <div id="register-form2">
                    <label class="form-label" for="name">이름</label>
                    <input class="form-control" type="text" maxlength='16' id="name" name="name" placeholder="이름">
                </div>
                <div id="register-form3">
                    <label class="form-label" for="gender">성별</label>
                    <label><input class="form-control" type="checkbox" id="gender" name="gender" value="male">남자</label>
                    <label><input class="form-control" type="checkbox" id="gender" name="gender" value="female">여자</label>
                </div>
                <div id="register-form4">
                    <label class="form-label" for="mobile">연락처</label>
                    <input class="form-control" type="tel" id="mobile" name="mobile" pattern="[0-9]{2,3}-[0-9]{3,4}-[0-9]{3,4}" placeholder="연락처">
                </div>
                <div id="register-form5">
                    <label class="form-label" for="birth">생년월일</label>
                    <input class="form-control" type="date" id="birth" name="birth" placeholder="생년월일">
                </div>
            </div>
            <button type="submit" id="register_button" style="margin-top: 20px">작가 등록 신청하기</button>
        </div>
</div>


</body>
</html>